#spring:
#  data:
#    mongodb:
# #     authentication-database:
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}
#      database: ${MONGO_DATABASE}
#      port: ${MONGO_PORT}
#      host: ${MONGO_HOST}
#  application:
#    name: category-service
#server:
#  port: 8083

  

spring:
  data:
    mongodb:
 #     authentication-database:
      database: categoryDB
      port: 27001
      host: localhost
  application:
    name: category-service
server:
  port: 8083